apiVersion: v1
kind: Service
metadata:
  name: mysql-auricula
  namespace: auricula
spec:
  type: NodePort
  selector:
    app: mysql-auricula
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
